backend:
  name: testNetlify
  repo: gbcrimson/hugo
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/galllery" # Media files will be stored in the repo under images/uploads

collections:
  - name: "food" # Used in routes, e.g., /admin/collections/blog
    label: "Food Item" # Used in the UI
    folder: "site/content/food" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Type", name: "type", widget: "string", default: "raw bar"}
      - {label: "Price", name: "price", widget: "string"}
